'use strict'

exports.VILLAGER = new Image()
exports.VILLAGER.src = require('../img/villager.png')
exports.VILLAGER_LUMBER = new Image()
exports.VILLAGER_LUMBER.src = require('../img/villager_lumber.png')
exports.VILLAGER_FOOD = new Image()
exports.VILLAGER_FOOD.src = require('../img/villager_food.png')
exports.VILLAGER_HUNGRY = new Image()
exports.VILLAGER_HUNGRY.src = require('../img/villager_hungry.png')

exports.HOUSE = new Image()
exports.HOUSE.src = require('../img/house.png')
exports.HOUSE_FOUNDATION = new Image()
exports.HOUSE_FOUNDATION.src = require('../img/house_foundation.png')
exports.HOUSE_FLOOR = new Image()
exports.HOUSE_FLOOR.src = require('../img/house_floor.png')

exports.FARM_UNPLANTED = new Image()
exports.FARM_UNPLANTED.src = require('../img/farm_unplanted.png')
exports.FARM_BARE = new Image()
exports.FARM_BARE.src = require('../img/farm_bare.png')
exports.FARM_SPROUTS = new Image()
exports.FARM_SPROUTS.src = require('../img/farm_sprouts.png')
exports.FARM_GROWING = new Image()
exports.FARM_GROWING.src = require('../img/farm_growing.png')
exports.FARM_MATURED = new Image()
exports.FARM_MATURED.src = require('../img/farm_matured.png')

exports.TREE = new Image()
exports.TREE.src = require('../img/tree.png')
exports.TREE_BROWN = new Image()
exports.TREE_BROWN.src = require('../img/tree_brown.png')
exports.TREE_UNPLANTED = new Image()
exports.TREE_UNPLANTED.src = require('../img/tree_unplanted.png')
exports.TREE_GROWING = new Image()
exports.TREE_GROWING.src = require('../img/tree_growing.png')

exports.DELETE = new Image()
exports.DELETE.src = require('../img/delete.png')
